"use client";

import { FormEvent, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowUpRight, Braces, Building2, Check, ChevronRight, Cloud, CloudCog, Code2, Database, Gauge, Layers3, Lightbulb, Mail, Menu, MessageSquare, Network, Palette, Rocket, Search, Send, Server, ShoppingBag, Sparkles, Target, TrendingUp, User, Workflow, X } from "lucide-react";
import { SiDatadog, SiDocker, SiFigma, SiGithubactions, SiGraphql, SiLaravel, SiMongodb, SiMysql, SiNextdotjs, SiNodedotjs, SiPhp, SiPostgresql, SiPrisma, SiPython, SiReact, SiTypescript } from "react-icons/si";
import { FaAws } from "react-icons/fa6";
import { TbBrandOpenai } from "react-icons/tb";
import { process, projects, services, solutions, technologyGroups } from "@/lib/data";

const iconMap = { brackets: Braces, layers: Layers3, sparkles: Sparkles, cloud: Cloud, server: Server, shopping: ShoppingBag, palette: Palette, cloudCog: CloudCog, workflow: Workflow, gauge: Gauge };

const techIconMap: Record<string, typeof SiReact> = {
  "Figma": SiFigma, "FigJam": SiFigma, "React": SiReact, "React Native": SiReact, "Next.js": SiNextdotjs, "TypeScript": SiTypescript,
  "PHP": SiPhp, "Laravel": SiLaravel, "Node.js": SiNodedotjs, "Python": SiPython, "PostgreSQL": SiPostgresql, "MySQL": SiMysql, "MongoDB": SiMongodb, "Prisma": SiPrisma,
  "OpenAI": TbBrandOpenai, "Vector databases": Database, "Workflow automation": Workflow, "Intelligent search": Search,
  "AWS": FaAws, "Docker": SiDocker, "GitHub Actions": SiGithubactions, "Datadog": SiDatadog, "GraphQL": SiGraphql, "REST": Network,
};

const processIcons = [Search, Target, Palette, Code2, Rocket, TrendingUp];

const techColorMap: Record<string, string> = {
  "Figma": "#F24E1E", "FigJam": "#FF7262", "React": "#61DAFB", "React Native": "#61DAFB", "Next.js": "#0b1220", "TypeScript": "#3178C6",
  "PHP": "#777BB4", "Laravel": "#FF2D20", "Node.js": "#5FA04E", "Python": "#3776AB", "PostgreSQL": "#336791", "MySQL": "#4479A1", "MongoDB": "#47A248", "Prisma": "#16A394",
  "OpenAI": "#10A37F", "Vector databases": "#12cde8", "Workflow automation": "#8b5cf6", "Intelligent search": "#2477ef",
  "AWS": "#FF9900", "Docker": "#2496ED", "GitHub Actions": "#2088FF", "Datadog": "#632CA6", "GraphQL": "#E10098", "REST": "#2477ef",
};

// function Mark() {
//   return <span className="brand-mark" aria-hidden="true"><span /><span /><span /><span /></span>;
// }

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: .65, delay, ease: [.22, 1, .36, 1] }}>{children}</motion.div>;
}

function Logo({ light = false }: { light?: boolean }) {
  return <a href="#top" className={`logo-link ${light ? "logo-light" : ""}`}><Image src={light ? "/tecton-logo-dark.svg" : "/tecton-logo.svg"} alt="Tecton Solutions" width={210} height={72} priority /></a>;
}

export default function Site() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState<(typeof projects)[number] | null>(null);
  const [formSent, setFormSent] = useState(false);
  const close = () => setMenuOpen(false);
  const submitContact = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const values = new FormData(event.currentTarget);
    const subject = encodeURIComponent(`Project enquiry from ${values.get("name")}`);
    const body = encodeURIComponent(`Name: ${values.get("name")}\nEmail: ${values.get("email")}\nCompany: ${values.get("company")}\n\n${values.get("message")}`);
    window.location.href = `mailto:hello@tectonsolutions.com?subject=${subject}&body=${body}`;
    setFormSent(true);
  };

  return <main id="top">
    <div className="nav-backdrop" />
    <header className="navbar"><div className="container nav-inner"><Logo /><nav className={menuOpen ? "nav-links open" : "nav-links"}>{[["Home", "#top"], ["Services", "#services"], ["Solutions", "#solutions"], ["Projects", "#projects"], ["About", "#about"], ["Contact", "#contact"]].map(([label, href]) => <a key={label} href={href} onClick={close}>{label}</a>)}<a className="nav-cta mobile-cta" href="#contact" onClick={close}>Let&apos;s talk <ArrowUpRight size={15} /></a></nav><a className="nav-cta desktop-cta" href="#contact">Let&apos;s talk <ArrowUpRight size={15} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></div></header>

    <section className="hero"><div className="hero-grid" /><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="container hero-layout"><div className="hero-copy"><motion.div className="eyebrow" initial={false} animate={{ opacity: 1, x: 0 }}>BUILDING THE FUTURE WITH TECHNOLOGY</motion.div><motion.h1 initial={false} animate={{ opacity: 1, y: 0 }}>Turning ideas into<br /><em>real solutions.</em></motion.h1><motion.p initial={false} animate={{ opacity: 1, y: 0 }}>We design and build modern digital products that help businesses innovate, automate, and scale.</motion.p><motion.div className="hero-actions" initial={false} animate={{ opacity: 1, y: 0 }}><a className="button button-gradient" href="#contact">Start a project <ArrowUpRight size={17} /></a></motion.div><motion.div className="trust-line" initial={false} animate={{ opacity: 1 }}>Web <i /> Mobile <i /> AI <i /> SaaS <i /> Cloud</motion.div></div><HeroVisual /></div></section>

    <section className="section intro" id="about"><div className="container intro-grid"><Reveal><h2>Technology built<br /><span>around your business.</span></h2></Reveal><Reveal delay={.1}><div className="intro-copy"><p className="lead">We don&apos;t simply build software. We understand the problem first, then create practical technology that moves your business forward.</p><p>From the first sketch to the systems that scale, Tecton is a focused technology partner for startups, SMEs and ambitious teams.</p><a className="text-link" href="#contact">Meet your technology partner <ArrowUpRight size={16} /></a></div></Reveal></div><div className="container feature-grid">{[["01", "Think", "Understand the problem before building the solution."], ["02", "Build", "Create scalable, secure and reliable digital products."], ["03", "Grow", "Optimize technology for long-term business growth."]].map(([num, title, text], i) => { const Icon = [Lightbulb, Code2, TrendingUp][i]; return <Reveal key={num} delay={i * .08}><div className={`feature feature-${i + 1}`}><span className="feature-icon"><Icon size={20} strokeWidth={1.5} /></span><h3>{title}</h3><p>{text}</p></div></Reveal> })}</div></section>

    <section className="section services-section" id="services"><div className="container"><Reveal><div className="section-heading"><h2>What we <span>build.</span></h2><p>Digital products with the right balance of imagination, engineering and business sense.</p></div></Reveal><div className="services-grid">{services.map((service, i) => { const Icon = iconMap[service.icon as keyof typeof iconMap]; return <Reveal key={service.number} delay={i * .05}><Link className={`service-card card-${i + 1}`} href={`/services/${service.slug}`}><div className="service-top"><Icon size={22} strokeWidth={1.5} /></div><h3>{service.title}</h3><p>{service.description}</p><span className="card-arrow"><ArrowUpRight size={17} /></span></Link></Reveal> })}</div></div></section>

    <section className="tech-strip"><div className="container tech-inner"><div><span className="eyebrow eyebrow-numbered">Our toolkit</span><h2>Powered by the <span>right technology.</span></h2><p className="tech-intro">From product thinking and design to AI, infrastructure and optimization, our toolkit follows the problem.</p></div><div className="tech-groups">{technologyGroups.map(([group, items]) => <div className="tech-group" key={group}><strong>{group}</strong><div className="tech-list">{items.map((tech) => { const TechIcon = techIconMap[tech]; return <span key={tech}>{TechIcon && <TechIcon size={16} style={{ color: techColorMap[tech] }} />}{tech}</span> })}</div></div>)}</div></div></section>

    <section className="dark-section solutions-section" id="solutions"><div className="dark-grid" /><div className="container solutions-layout"><Reveal><h2>From complex problems<br />to <span>simple solutions.</span></h2><p className="dark-lead">The best technology feels clear. We turn complexity into products people understand, use and love.</p><a className="button button-light" href="#contact">Start a conversation <ArrowUpRight size={17} /></a></Reveal><Reveal delay={.12}><div className="solutions-list">{solutions.map((solution) => <a className="solution-item" href="#contact" key={solution}><strong>{solution}</strong><ArrowUpRight size={18} /></a>)}</div></Reveal></div><div className="glow-ring" /></section>

    <section className="section process-section"><div className="container"><Reveal><div className="section-heading"><h2>How we <span>work.</span></h2><p>Clear thinking, open communication and a process built to keep momentum.</p></div></Reveal><div className="process-grid"><div className="process-track" />{process.map(([num, title, text], i) => { const Icon = processIcons[i]; return <Reveal key={num} delay={i * .05}><div className={`process-item process-item-${i + 1}`}><span className="process-icon"><Icon size={18} strokeWidth={1.75} /></span><h3>{title}</h3><p>{text}</p></div></Reveal> })}</div></div></section>

    {/* <section className="section projects-section" id="projects"><div className="container"><Reveal><div className="section-heading"><h2>Ideas made <span>real.</span></h2><p>A glimpse into the kind of digital products we love to bring to life.</p></div></Reveal><div className="projects-grid">{projects.map((project, i) => <Reveal key={project.title} delay={i * .08}><article className={`project-card project-${project.tone}`}><div className={`project-preview${project.image ? " project-preview-photo" : ""}`}>{project.image ? <Image className="project-preview-image" src={project.image} alt={project.title} fill sizes="(max-width: 800px) 100vw, 380px" /> : <div className="preview-window"><div className="preview-dots"><i /><i /><i /></div><div className="preview-content"><span>{project.category.toUpperCase()}</span><b>{project.title.split(" ")[0]}<br />{project.title.split(" ").slice(1).join(" ")}</b><div className="preview-bars"><i /><i /><i /></div></div></div>}</div><div className="project-meta"><span>{project.category}</span><h3>{project.title}</h3><p>{project.description}</p><div className="project-bottom"><div>{project.tags.map(tag => <small key={tag}>{tag}</small>)}</div><button type="button" onClick={() => setSelectedProject(project)} aria-label={`View ${project.title}`}><ArrowUpRight size={18} /></button></div></div></article></Reveal>)}</div></div></section> */}

    <section className="why-section"><div className="container why-grid"><Reveal><h2>Built for the<br /><span>long game.</span></h2><p className="dark-lead">Great products are never finished. They evolve with your customers, your team and the opportunity ahead.</p><ul className="check-list">{["Business-focused development", "Scalable architecture", "Modern technology", "Clean and maintainable code", "Security-first approach", "Performance optimization", "Long-term technical partnership"].map(item => <li key={item}><Check size={15} />{item}</li>)}</ul></Reveal><Reveal delay={.15}><div className="why-visual"><div className="visual-label">TECTON / SOLUTIONS</div><div className="visual-core"><Code2 size={42} strokeWidth={1} /><span>ideas</span><span>technology</span><span>solutions</span></div><div className="visual-orbit orbit-a" /><div className="visual-orbit orbit-b" /></div></Reveal></div></section>

    <section className="built-section"><div className="container built-inner"><div><h2>Built for what&apos;s <span>next.</span></h2></div><div className="built-list"><span>Startups</span><span>Growing businesses</span><span>Digital products</span><span>Enterprise solutions</span></div></div></section>

    <section className="cta-section" id="contact"><div className="cta-grid" /><div className="cta-orb orb-a" /><div className="cta-orb orb-b" /><div className="container cta-inner"><div className="cta-copy"><h2>Have an idea?<br /><span>Let&apos;s build it.</span></h2><p>Tell us what you&apos;re building, what you&apos;re solving, or where you want to go. We&apos;ll help turn the idea into a real digital product.</p><div className="contact-card"><div className="contact-card-top"><span className="contact-card-kicker"><i />Send us a message</span><span className="contact-card-note">We reply within 24h</span></div><form className="contact-form" onSubmit={submitContact}><div className="field"><label htmlFor="name">Name</label><div className="field-control"><User size={15} /><input required id="name" name="name" placeholder="Your name" /></div></div><div className="field"><label htmlFor="email">Email</label><div className="field-control"><Mail size={15} /><input required type="email" id="email" name="email" placeholder="you@company.com" /></div></div><div className="field"><label htmlFor="company">Company</label><div className="field-control"><Building2 size={15} /><input id="company" name="company" placeholder="Company name" /></div></div><div className="field form-wide"><label htmlFor="message">What are you building?</label><div className="field-control field-control-textarea"><MessageSquare size={15} /><textarea required id="message" name="message" rows={4} placeholder="A little about your project..." /></div></div><button className="button button-gradient form-submit" type="submit">{formSent ? "Email draft ready" : "Start a conversation"} {formSent ? <Check size={17} /> : <Send size={16} />}</button></form></div></div><div className="cta-visual"><motion.div className="cta-mark" animate={{ y: [0, -10, 0] }} transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}><motion.div className="cta-mark-icon" animate={{ opacity: [1, .35, 1], scale: [1, 1.08, 1] }} transition={{ duration: 1.6, repeat: Infinity, ease: "easeInOut" }}><Lightbulb size={72} strokeWidth={1.2} /></motion.div><span>ideas / systems</span></motion.div><div className="cta-ring ring-a" /><div className="cta-ring ring-b" /><motion.div className="cta-chip chip-top" animate={{ y: [0, -8, 0] }} transition={{ duration: 4, repeat: Infinity }}><Sparkles size={13} /> Free consultation</motion.div><motion.div className="cta-chip chip-bottom" animate={{ y: [0, 8, 0] }} transition={{ duration: 5, repeat: Infinity }}><Check size={13} /> Reply within 24h</motion.div></div></div></section>

    <footer className="footer"><div className="container"><div className="footer-top"><Logo light /><p>Ideas / technology / real solutions.</p><a className="back-top" href="#top">Back to top <ArrowUpRight size={15} /></a></div><div className="footer-cols"><div><span>Company</span><a href="#about">About</a><a href="#services">Services</a><a href="#projects">Projects</a><a href="#contact">Contact</a></div><div><span>Services</span>{services.slice(0, 4).map(service => <Link key={service.slug} href={`/services/${service.slug}`}>{service.title}</Link>)}</div><div><span>Connect</span><a href="https://www.linkedin.com/company/tecton-solutions/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://www.instagram.com/tectonsolutions/" target="_blank" rel="noreferrer">Instagram</a><a href="https://github.com/tecton-solutions" target="_blank" rel="noreferrer">GitHub</a></div><div className="footer-note"><span>Let&apos;s make something<br /><em>meaningful.</em></span><ArrowUpRight size={22} /></div></div><div className="footer-bottom"><span>© 2026 Tecton Solutions. All rights reserved.</span><span>Built with intention.</span></div></div></footer>
    {selectedProject && <div className="project-modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-dialog-title" onClick={event => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setSelectedProject(null)} aria-label="Close case study"><X size={18} /></button><span>{selectedProject.category}</span><h2 id="project-dialog-title">{selectedProject.title}</h2><p>{selectedProject.detail}</p><div>{selectedProject.tags.map(tag => <small key={tag}>{tag}</small>)}</div><a className="button button-dark" href="#contact" onClick={() => setSelectedProject(null)}>Discuss a similar project <ArrowUpRight size={16} /></a></div></div>}
  </main>;
}

function HeroVisual() { return <div className="hero-visual"><motion.div className="visual-grid-card" style={{ transformPerspective: 900 }} initial={{ y: 0, rotateY: -13, rotateX: 5, rotateZ: 0 }} animate={{ y: [0, -14, 0], rotateY: [-13, -8, -13], rotateX: [5, 8, 5], rotateZ: [0, 1.4, 0] }} transition={{ duration: 7, repeat: Infinity, ease: "easeInOut" }}><div className="grid-card-top"><span>TECTON / CORE</span><span className="live-dot">LIVE</span></div><div className="grid-stats"><div className="grid-stat"><span>Innovate</span><b>24+</b><small>ideas</small></div><div className="grid-stat"><span>Automate</span><b>340+</b><small>flows</small></div><div className="grid-stat"><span>Scale</span><b>3.2x</b><small>growth</small></div></div><div className="grid-card-chart"><div className="chart-bars">{[42, 64, 50, 80, 58, 72].map((h, i) => <motion.i key={i} initial={{ height: `${h}%` }} animate={{ height: [`${h}%`, `${Math.min(h + 22, 96)}%`, `${h}%`] }} transition={{ duration: 2.6, repeat: Infinity, delay: i * .15, ease: "easeInOut" }} />)}</div><div className="chart-footer"><span>IDEAS SHIPPED</span><b>128 <small>↑ 18.4%</small></b></div></div></motion.div><motion.div className="floating-chip chip-one" animate={{ y: [0, -8, 0] }} transition={{ duration: 4, repeat: Infinity }}><Sparkles size={15} /> AI / AUTOMATION</motion.div><motion.div className="floating-chip chip-two" animate={{ y: [0, 8, 0] }} transition={{ duration: 5, repeat: Infinity }}><span className="chip-pulse" /> SYSTEMS ONLINE</motion.div><div className="hero-arc arc-one" /><div className="hero-arc arc-two" /></div> }
